/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as AnalysisIdIndexRouteImport } from './routes/analysis.$id.index'
import { Route as AnalysisIdProcessingRouteImport } from './routes/analysis.$id.processing'
import { Route as AnalysisIdReportRouteImport } from './routes/analysis.$id.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdIndexRoute = AnalysisIdIndexRouteImport.update({
  id: '/analysis/$id/',
  path: '/analysis/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdProcessingRoute = AnalysisIdProcessingRouteImport.update({
  id: '/analysis/$id/processing',
  path: '/analysis/$id/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdReportRoute = AnalysisIdReportRouteImport.update({
  id: '/analysis/$id/report',
  path: '/analysis/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/investigations': typeof InvestigationsRoute
  '/analysis/$id/processing': typeof AnalysisIdProcessingRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
  '/analysis/$id/': typeof AnalysisIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/investigations': typeof InvestigationsRoute
  '/analysis/$id/processing': typeof AnalysisIdProcessingRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
  '/analysis/$id': typeof AnalysisIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/investigations': typeof InvestigationsRoute
  '/analysis/$id/processing': typeof AnalysisIdProcessingRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
  '/analysis/$id/': typeof AnalysisIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/investigations'
    | '/analysis/$id/processing'
    | '/analysis/$id/report'
    | '/analysis/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/investigations'
    | '/analysis/$id/processing'
    | '/analysis/$id/report'
    | '/analysis/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/investigations'
    | '/analysis/$id/processing'
    | '/analysis/$id/report'
    | '/analysis/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRoute
  InvestigationsRoute: typeof InvestigationsRoute
  AnalysisIdProcessingRoute: typeof AnalysisIdProcessingRoute
  AnalysisIdReportRoute: typeof AnalysisIdReportRoute
  AnalysisIdIndexRoute: typeof AnalysisIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id/': {
      id: '/analysis/$id/'
      path: '/analysis/$id'
      fullPath: '/analysis/$id/'
      preLoaderRoute: typeof AnalysisIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id/processing': {
      id: '/analysis/$id/processing'
      path: '/analysis/$id/processing'
      fullPath: '/analysis/$id/processing'
      preLoaderRoute: typeof AnalysisIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id/report': {
      id: '/analysis/$id/report'
      path: '/analysis/$id/report'
      fullPath: '/analysis/$id/report'
      preLoaderRoute: typeof AnalysisIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRoute,
  InvestigationsRoute: InvestigationsRoute,
  AnalysisIdProcessingRoute: AnalysisIdProcessingRoute,
  AnalysisIdReportRoute: AnalysisIdReportRoute,
  AnalysisIdIndexRoute: AnalysisIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
